apiVersion: v1
kind: Pod
metadata:
  name: ingot
  namespace: gold
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh", "-c"]
    resources: #must be specified as the quota is specified in the namespace and no limit range created to be default
      requests:
        memory: "200Mi"
      limits:
        memory: "400Mi"
